#!/bin/sh

### BEGIN INIT INFO
# Provides:        tooltron
# Required-Start:
# Required-Stop:
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Tooltron daemon
### END INIT INFO

case "$1" in
  start)
    (cd /root; tooltron run >> tooltron.log)&
    ;;
  stop)
    tooltron stop
    ;;
  reload)
    tooltron refresh
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/tooltron {start|stop|restart|reload}"
    exit 1
esac
